language: python
python:
- 2.7
install:
- mkdir -p buildout-cache/{eggs,downloads}
- python bootstrap.py
- bin/buildout -c travis.cfg -N -q -t 3
script:
- bin/test
- ./bin/createcoverage run ./bin/test -t \!robot
after_success:
- pip install coveralls
- coveralls
after_script:
- kill $JAVA_PID
notifications:
  email:
  - travis-reports@ecreall.com
